SELECT
	*
FROM
	CUSTOMER
	--Q1. What is the total revenue generated by male vs. female customers?
SELECT
	GENDER,
	SUM(PURCHASE_AMOUNT) AS REVENUE
FROM
	CUSTOMER
GROUP BY
	GENDER
	--Q2. Which customers used a discount but still spent more than the average purchase amount.
SELECT
	CUSTOMER_ID,
	PURCHASE_AMOUNT
FROM
	CUSTOMER
WHERE
	DISCOUNT_APPLIED = 'Yes'
	AND PURCHASE_AMOUNT > (
		SELECT
			AVG(PURCHASE_AMOUNT)
		FROM
			CUSTOMER
	)
	--Q3- Which are the top 5 products with the highest average review ratings.
SELECT
	ITEM_PURCHASED,
	ROUND(AVG(REVIEW_RATING::NUMERIC), 2) AS AVG_PRODUCT_RATING
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	AVG(REVIEW_RATING) DESC
LIMIT
	5
	--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
	SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVG_PURCHASE_AMOUNT
FROM
	CUSTOMER
WHERE
	SHIPPING_TYPE = 'Standard'
	OR SHIPPING_TYPE = 'Express'
GROUP BY
	SHIPPING_TYPE
	--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
	ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVG_SPEND,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	SUBSCRIPTION_STATUS
	--Q6. Which 5 products have the highest percentage of purchase with discounts applied?
SELECT
	ITEM_PURCHASED,
	SUM(PURCHASE_AMOUNT) AS HIGHEST_PURCHASE
FROM
	CUSTOMER
WHERE
	DISCOUNT_APPLIED = 'Yes'
GROUP BY
	ITEM_PURCHASED
ORDER BY
	HIGHEST_PURCHASE DESC
LIMIT
	5
	--Q7. Segment customers into NEW, Returning, and royal based on their total number of previous purchase, and show the count of each segment.
WITH
	CUSTOMER_TYPE AS (
		SELECT
			CUSTOMER_ID,
			PREVIOUS_PURCHASES,
			CASE
				WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
				WHEN PREVIOUS_PURCHASES >= 2
				AND PREVIOUS_PURCHASES <= 10 THEN 'Returning'
				ELSE 'Loyal'
			END AS CUSTOMER_SEGMENT
		FROM
			CUSTOMER
	)
SELECT
	CUSTOMER_SEGMENT,
	COUNT(*) AS "Number of Customers"
FROM
	CUSTOMER_TYPE
GROUP BY
	CUSTOMER_SEGMENT
	--Q8. What are the top 3 most purchased products within each category.
WITH
	ITEM_COUNTS AS (
		SELECT
			CATEGORY,
			ITEM_PURCHASED,
			COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
			ROW_NUMBER() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					COUNT(CUSTOMER_ID) DESC
			) AS ITEM_RANK
		FROM
			CUSTOMER
		GROUP BY
			CATEGORY,
			ITEM_PURCHASED
	)
SELECT
	ITEM_RANK,
	CATEGORY,
	ITEM_PURCHASED,
	TOTAL_ORDERS
FROM
	ITEM_COUNTS
WHERE
	ITEM_RANK <= 3
	--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscibe?
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM
	CUSTOMER
WHERE
	PREVIOUS_PURCHASES > 5
GROUP BY
	SUBSCRIPTION_STATUS
	--Q10. What is the revenue contribution of each age group.
SELECT
	AGE_GROUP,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	AGE_GROUP
ORDER BY
	TOTAL_REVENUE DESC
